name: Release on Gitea

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Gitea release
        uses: https://gitea.com/actions/gitea-release-action@v1
        with:
          token: ${{ secrets.TOKEN_GITEA }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: changelogs/${{ github.ref_name }}.md
